Traceback (most recent call last):
  File "/home/lucas/Consulta_Escola/main.py", line 186, in <module>
    window = App()
             ^^^^^
  File "/home/lucas/Consulta_Escola/main.py", line 50, in __init__
    self.ufs = self.df['UF'].unique().tolist()
               ^^^^^^^
AttributeError: 'App' object has no attribute 'df'
Traceback (most recent call last):
  File "/home/lucas/Consulta_Escola/main.py", line 186, in <module>
    window = App()
             ^^^^^
  File "/home/lucas/Consulta_Escola/main.py", line 48, in __init__
    self.ufs = self.df['UF'].unique().tolist()
               ^^^^^^^
AttributeError: 'App' object has no attribute 'df'
